### ISSUE TITLE
about register paths ?

### ISSUE THREAD

**Issue by elkhadirzyad** [steinarb/ukelonn#5]
hello,

i have the same issue as you (https://groups.google.com/g/ops4j/c/FBr14YMEU3I) you said that you register 2 paths, can u give more details , thanks.

**Comment by steinarb** [comment]
Hi,

I haven't used vaadin since 2018, and I don't remember what I meant by registering 2 paths.

In my current setup I create [a ServletContextHelper that plugs in to the web whiteboard](https://github.com/steinarb/ukelonn/blob/master/ukelonn.web.security/src/main/java/no/priv/bang/ukelonn/web/security/UkelonnServletContextHelper.java#L7)

I then refer to that web context in serlvets and filters pluggng into the web whiteboard:

- https://github.com/steinarb/ukelonn/blob/master/ukelonn.web.security/src/main/java/no/priv/bang/ukelonn/web/security/UkelonnShiroFilter.java#L40
- https://github.com/steinarb/ukelonn/blob/master/ukelonn.web.services/src/main/java/no/priv/bang/ukelonn/api/UkelonnRestApiServlet.java#L30
- https://github.com/steinarb/ukelonn/blob/master/ukelonn.web.frontend/src/main/java/no/priv/bang/ukelonn/web/frontend/UkelonnServlet.java#L27

**Comment by elkhadirzyad** [comment]
Thank u for ur answer,
Here is my situation, when i type (localhost:8181) it should normally give me the karaf welcome page. instead of that it redirects me to localhost:8181/app/welcome.
this path is defined in my bundle.
to register my servlet i used 
webS.registerServlet(new HttpServletDispatcher(), "welcome", new String[] {"/api/welcome/*" }, initParamsW, httpContext);

I want to define the contextPath for my servlet but i don't know how to do it

**Comment by steinarb** [comment]
This isn't really an issue so I'm closing it.

I've opened a discussion forum on the project and further discussions can take place there.
